#Neo4j configuration
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${neo4j.username}
      password: ${neo4j.password}

#Actuator
management:
  endpoint:
    health:
      show-details: always